### ISSUE TITLE
Package incompatible with probot@~11.0.0

### ISSUE THREAD

**Issue by jonathanagosto** [probot/metadata#22]
Using the latest version of probot (v11.0.1 at this time), this package (v2.0.0) seems incompatible?. The `probot-metadata` constructor receives a `context`, which is used to declare `const github = context.github`, but such property doesn't exists in `context`. For now, I've monkey patched the library replacing the declaration to:

```js
const github = context.octokit
// const github = context.github
```

**Comment by gr2m** [comment]
It's `context.octokit` now. I can review a pull request if would like to send one. We could probably make the extension work with v11 without breaking the current usage

**Comment by jonathanagosto** [comment]
Hey @gr2m, Ive created the following Pull Request:

https://github.com/probot/metadata/pull/23

Let me know if I need to change anything!
