### ISSUE TITLE
Malformed HTML comment on edge case content

### ISSUE THREAD

**Issue by gimenete** [probot/metadata#9]
I've tried an edge case using:

```js
await metadata(context).set('key', 'value -->')
```

It generates this code:

```html
<!-- probot = {"1":{"key":"value -->"}} -->
```

The result is that the HTML comment is not finished where we wanted. I was wondering if this was just fine for the GitHub's Markdown parser, but as you can see in this screenshot the preview is broken:

![screen shot 2018-06-26 at 20 03 50](https://user-images.githubusercontent.com/50486/41930780-5ec75cd4-797c-11e8-93bd-dea213798862.png)

Based on the spec the problem is the `--`, not the `>`, but escaping the `>` with `&gt;` seems to work fine for the GitHub preview at least. However any `&` should be escaped to not break metadata with "&gt;", etc.

For a more robust solution one solution is to convert the JSON string to base64. The problem is that it makes the comment not readable by humans

A super simple solution would be to break any `--` into `-\n-` and then removing any line feed when parsing. The benefits are:

- `JSON.stringify()` without arguments never contains line feeds so we know that the only line feeds are the ones we add
- A comment in HTML can contain multiple lines so it is not malformed HTML
- It is backwards compatible with existing apps using `metadata`
- It keeps the content human readable (unlike base64)

**Comment by bkeepers** [comment]
Thanks for the detailed issue, @gimenete! 

Human-readability is not a requirement for any of my use cases. I had been thinking about using JWT or some other mechanism to sign the payloads to prevent tampering anyway, so I'm not opposed to going the base64 route.

I'd be happy to review a PR that includes any solution to this.

**Comment by gimenete** [comment]
I can create a PR in the next few days. I'll use the `jsonwebtoken`.

Based on https://github.com/probot/metadata/issues/8 I'll try to load and use the certificate of the GitHub app. I'll take a look to `probot` to see how it loads it.

**Comment by gimenete** [comment]
I found this https://github.com/probot/probot/blob/master/src/private-key.ts I'll use the same logic, but it would be great to have that exposed from the `context` somehow

**Comment by gimenete** [comment]
I got some time today and made a PR.
